version: "3.4"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend
    ports:
      - "57185:80"
  frontend:
    build:
      context: ./AppFront
      dockerfile: Dockerfile
    image: frontend
    ports:
      - "4200:80"
