version: "3.4"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend
    ports:
      - "8080:80"
  frontend:
    build:
      context: ./AppFront
      dockerfile: Dockerfile
    image: frontend
    ports:
      - "8080:4200"



# version: "3.4"
# services:
#   backend:
#     image: backend
#     ports:
#       - "44303:44303"
#   frontend:
#     image: frontend
#     ports:
#       - "4200:4200"

