version: "3.4"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend
    ports:
      - "57185:80"
  frontend:
    build:
      context: ./AppFront
      dockerfile: Dockerfile
    image: frontend
    ports:
      - "4200:80"
     


# version: "3.4"
# services:
#   backend:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     image: backend
#     ports:
#       - "8080:80"
#   frontend:
#     build:
#       context: ./Hahn.ApplicationProcess.February2021.Web/WepAppFront
#       dockerfile: Dockerfile
#     image: frontend
#     ports:
#       - "4200:8080"


